import type {
  DatasetRecord,
  DatasetFieldSchema,
  Workflow,
  WorkflowProgressSnapshot,
  UserCreditAccount,
  CreditLedgerEntry,
  PlannerPlan,
} from '@/core/contracts';

export const INITIAL_CREDIT_ACCOUNT: UserCreditAccount = {
  userId: 'unavailable',
  balanceUsd: 0.00,
  reservedUsd: 0.00,
  availableUsd: 0.00,
  currency: 'USD',
  updatedAt: new Date().toISOString(),
};

export const INITIAL_LEDGER_ENTRIES: CreditLedgerEntry[] = [];

export const DEMO_FIELDS: DatasetFieldSchema[] = [
  { name: 'company_name', type: 'string', description: 'Legal / brand name of company', required: true },
  { name: 'funding_amount_usd', type: 'number', description: 'Total funding amount announced', required: true },
  { name: 'stage', type: 'string', description: 'Latest verified funding round', required: true },
  { name: 'founders', type: 'array', description: 'Identified founding team members', required: true },
  { name: 'headquarters', type: 'string', description: 'Primary operating location', required: false },
  { name: 'verified_website', type: 'url', description: 'Official canonical website domain', required: true },
  { name: 'technical_focus', type: 'string', description: 'Core AI / infrastructure niche', required: false },
  { name: 'premium_telemetry', type: 'string', description: 'x402 Verified benchmark telemetry', required: false },
];

export const DEMO_PLAN: PlannerPlan = {
  summary:
    'Discover top early-stage AI infrastructure startups founded in 2024, extract verified funding rounds, validate founder identities, and pull premium benchmark telemetry via x402 on Base Sepolia.',
  fields: DEMO_FIELDS,
  totalEstimatedCostUsd: 0.045,
  tasks: [
    {
      id: 'task-discover-startups',
      name: 'Discover AI Infrastructure Startups (2024)',
      type: 'discovery',
      description: 'Search Exa for companies matching criteria and collect primary press releases',
      dependencies: [],
      completionPolicy: 'all_succeeded',
      input: { query: 'AI infrastructure developer tools series A seed 2024 funding announcement', numResults: 15 },
      expectedArtifactTypes: ['source'],
      estimatedCostUsd: 0.005,
    },
    {
      id: 'task-extract-funding',
      name: 'Extract Round Details & Founders',
      type: 'extraction',
      description: 'Extract structured funding rounds, valuations, and verified founder profiles',
      dependencies: ['task-discover-startups'],
      completionPolicy: 'allow_partial',
      input: { fields: ['company_name', 'funding_amount_usd', 'stage', 'founders'] },
      expectedArtifactTypes: ['record_slice'],
      estimatedCostUsd: 0.010,
    },
    {
      id: 'task-x402-premium-data',
      name: 'Acquire Benchmark Telemetry via x402',
      type: 'browser_navigation',
      description: 'Execute genuine x402 micropayment on Base Sepolia treasury for benchmark telemetry',
      dependencies: ['task-extract-funding'],
      completionPolicy: 'allow_partial',
      input: { resourceUri: 'kyros-demo://premium-eval/latency-benchmarks', maxSpendUsd: 0.02 },
      expectedArtifactTypes: ['record_slice'],
      estimatedCostUsd: 0.020,
    },
    {
      id: 'task-validate-quality',
      name: 'Validate Types & Source Provenance',
      type: 'quality_validation',
      description: 'Verify all extracted claims are supported by source snippets or marked missing',
      dependencies: ['task-extract-funding', 'task-x402-premium-data'],
      completionPolicy: 'allow_partial',
      input: { strictUrlValidation: true },
      expectedArtifactTypes: ['record_slice'],
      estimatedCostUsd: 0.005,
    },
    {
      id: 'task-deduplicate',
      name: 'Deduplicate & Join Dataset',
      type: 'deduplication',
      description: 'Merge candidate entity mentions and resolve conflicts',
      dependencies: ['task-validate-quality'],
      completionPolicy: 'all_succeeded',
      input: { dedupeKeys: ['company_name', 'verified_website'] },
      expectedArtifactTypes: ['dataset'],
      estimatedCostUsd: 0.005,
    },
  ],
};

export const DEMO_WORKFLOW: Workflow = {
  id: 'wf-ai-startups',
  runId: 'run-ai-startups-1',
  userId: 'usr_clerk_demo_8829',
  prompt: 'Top AI infrastructure startups founded in 2024 with funding amounts, verified founders, and benchmark telemetry',
  status: 'completed',
  summary: DEMO_PLAN.summary,
  fieldSchema: DEMO_FIELDS,
  budgetPolicy: {
    maxSpendUsd: 0.05,
    perCallCeilingUsd: 0.02,
    currency: 'USD',
    allowPaidSources: true,
  },
  timestamps: {
    createdAt: '2026-09-25T14:00:00.000Z',
    updatedAt: '2026-09-25T14:06:30.000Z',
    startedAt: '2026-09-25T14:00:10.000Z',
    finishedAt: '2026-09-25T14:06:30.000Z',
  },
};

export const DEMO_PROGRESS_SNAPSHOT: WorkflowProgressSnapshot = {
  workflowId: 'wf-ai-startups',
  runId: 'run-ai-startups-1',
  status: 'completed',
  progressPercent: 100,
  totalTasks: 5,
  completedTasks: 5,
  failedTasks: 0,
  updatedAt: '2026-09-25T14:06:30.000Z',
  tasks: [
    {
      id: 'task-discover-startups',
      name: 'Discover AI Infrastructure Startups (2024)',
      type: 'discovery',
      status: 'succeeded',
      attemptCounts: { domain: 1, infrastructure: 1 },
      startedAt: '2026-09-25T14:00:10.000Z',
      finishedAt: '2026-09-25T14:01:20.000Z',
    },
    {
      id: 'task-extract-funding',
      name: 'Extract Round Details & Founders',
      type: 'extraction',
      status: 'succeeded',
      attemptCounts: { domain: 1, infrastructure: 1 },
      startedAt: '2026-09-25T14:01:21.000Z',
      finishedAt: '2026-09-25T14:03:10.000Z',
    },
    {
      id: 'task-x402-premium-data',
      name: 'Acquire Benchmark Telemetry via x402',
      type: 'browser_navigation',
      status: 'succeeded',
      attemptCounts: { domain: 1, infrastructure: 1 },
      startedAt: '2026-09-25T14:03:12.000Z',
      finishedAt: '2026-09-25T14:04:45.000Z',
    },
    {
      id: 'task-validate-quality',
      name: 'Validate Types & Source Provenance',
      type: 'quality_validation',
      status: 'succeeded',
      attemptCounts: { domain: 1, infrastructure: 1 },
      startedAt: '2026-09-25T14:04:46.000Z',
      finishedAt: '2026-09-25T14:05:30.000Z',
    },
    {
      id: 'task-deduplicate',
      name: 'Deduplicate & Join Dataset',
      type: 'deduplication',
      status: 'succeeded',
      attemptCounts: { domain: 1, infrastructure: 1 },
      startedAt: '2026-09-25T14:05:31.000Z',
      finishedAt: '2026-09-25T14:06:30.000Z',
    },
  ],
};

export const DEMO_RECORDS: DatasetRecord[] = [
  {
    id: 'rec-kyros-01',
    workflowId: 'wf-ai-startups',
    runId: 'run-ai-startups-1',
    data: {
      company_name: 'Cognition AI',
      funding_amount_usd: 175000000,
      stage: 'Series A',
      founders: ['Scott Wu', 'Steven Hao', 'Walden Yan'],
      headquarters: 'San Francisco, CA / Salt Lake City, UT',
      verified_website: 'https://cognition.ai',
      technical_focus: 'Autonomous Software Engineering Agent (Devin)',
      premium_telemetry: 'SWE-bench verified resolved rate: 13.86%, TTFT latency: 340ms',
    },
    evidence: {
      company_name: {
        value: 'Cognition AI',
        supportState: 'supported',
        sourceUrl: 'https://techcrunch.com/2024/04/24/cognition-ai-lands-175m-series-a-at-2b-valuation/',
        sourceTitle: 'Cognition lands $175M at $2B valuation led by Founders Fund',
        snippet: 'Cognition, the AI startup behind the coding assistant Devin, has raised $175 million in a Series A round.',
        collectedAt: '2026-09-25T14:02:15.000Z',
        acquisitionMethod: 'exa_search',
      },
      funding_amount_usd: {
        value: 175000000,
        supportState: 'supported',
        sourceUrl: 'https://techcrunch.com/2024/04/24/cognition-ai-lands-175m-series-a-at-2b-valuation/',
        sourceTitle: 'TechCrunch Series A Coverage',
        snippet: 'Cognition has closed a $175M Series A round, bringing total capital to over $196 million.',
        collectedAt: '2026-09-25T14:02:15.000Z',
        acquisitionMethod: 'exa_search',
      },
      stage: {
        value: 'Series A',
        supportState: 'supported',
        sourceUrl: 'https://techcrunch.com/2024/04/24/cognition-ai-lands-175m-series-a-at-2b-valuation/',
        sourceTitle: 'TechCrunch Series A Coverage',
        snippet: '...in a Series A financing round led by Founders Fund.',
        collectedAt: '2026-09-25T14:02:15.000Z',
        acquisitionMethod: 'exa_search',
      },
      founders: {
        value: ['Scott Wu', 'Steven Hao', 'Walden Yan'],
        supportState: 'supported',
        sourceUrl: 'https://www.forbes.com/sites/alexkonrad/2024/03/12/meet-cognition-ai-the-startup-behind-ai-coder-devin/',
        sourceTitle: 'Meet Cognition AI, The Startup Behind AI Coder Devin',
        snippet: 'Founders include Scott Wu (CEO), Steven Hao, and Walden Yan, former competitive programmers.',
        collectedAt: '2026-09-25T14:02:30.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      headquarters: {
        value: 'San Francisco, CA / Salt Lake City, UT',
        supportState: 'partially_supported',
        sourceUrl: 'https://www.forbes.com/sites/alexkonrad/2024/03/12/meet-cognition-ai-the-startup-behind-ai-coder-devin/',
        snippet: 'Cognition operates distributed offices between Utah and San Francisco.',
        collectedAt: '2026-09-25T14:02:30.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      verified_website: {
        value: 'https://cognition.ai',
        supportState: 'supported',
        sourceUrl: 'https://cognition.ai',
        snippet: 'Official homepage of Cognition AI.',
        collectedAt: '2026-09-25T14:02:35.000Z',
        acquisitionMethod: 'exa_search',
      },
      technical_focus: {
        value: 'Autonomous Software Engineering Agent (Devin)',
        supportState: 'supported',
        sourceUrl: 'https://cognition.ai/blog/introducing-devin',
        snippet: 'Introducing Devin, the first fully autonomous AI software engineer.',
        collectedAt: '2026-09-25T14:02:40.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      premium_telemetry: {
        value: 'SWE-bench verified resolved rate: 13.86%, TTFT latency: 340ms',
        supportState: 'supported',
        sourceUrl: 'https://basescan.org/tx/0x89e2c608f62f3a8bf1d7644265435985098ff456e30b691b34fa394ba0577dae',
        sourceTitle: 'x402 Verified Benchmark Resource (Base Sepolia)',
        snippet: 'Settled 0.008 ETH payment for private benchmark telemetry feed.',
        collectedAt: '2026-09-25T14:04:12.000Z',
        acquisitionMethod: 'x402_paid',
        costUsd: 0.02,
        transactionReceipt: {
          hash: '0x89e2c608f62f3a8bf1d7644265435985098ff456e30b691b34fa394ba0577dae',
          network: 'Base Sepolia (84532)',
          status: 'confirmed',
          resourceUri: 'kyros-demo://premium-eval/latency-benchmarks',
          amountUsd: 0.02,
        },
      },
    },
    createdAt: '2026-09-25T14:06:00.000Z',
    updatedAt: '2026-09-25T14:06:30.000Z',
  },
  {
    id: 'rec-kyros-02',
    workflowId: 'wf-ai-startups',
    runId: 'run-ai-startups-1',
    data: {
      company_name: 'Perplexity AI',
      funding_amount_usd: 73600000,
      stage: 'Series B',
      founders: ['Aravind Srinivas', 'Denis Yarats', 'Johnny Ho', 'Andy Konwinski'],
      headquarters: 'San Francisco, CA',
      verified_website: 'https://perplexity.ai',
      technical_focus: 'Conversational Answer Engine & Live Web Grounding',
      premium_telemetry: null,
    },
    evidence: {
      company_name: {
        value: 'Perplexity AI',
        supportState: 'supported',
        sourceUrl: 'https://techcrunch.com/2024/01/04/perplexity-ai-raises-73-6m-series-b/',
        sourceTitle: 'Perplexity AI raises $73.6M Series B led by IVP',
        snippet: 'Perplexity has raised $73.6 million in Series B funding from institutional investors.',
        collectedAt: '2026-09-25T14:02:18.000Z',
        acquisitionMethod: 'exa_search',
      },
      funding_amount_usd: {
        value: 73600000,
        supportState: 'supported',
        sourceUrl: 'https://techcrunch.com/2024/01/04/perplexity-ai-raises-73-6m-series-b/',
        snippet: '...Series B funding round totaling $73.6 million valuing the company at $520 million.',
        collectedAt: '2026-09-25T14:02:18.000Z',
        acquisitionMethod: 'exa_search',
      },
      stage: {
        value: 'Series B',
        supportState: 'supported',
        sourceUrl: 'https://techcrunch.com/2024/01/04/perplexity-ai-raises-73-6m-series-b/',
        snippet: 'Series B announced in early 2024.',
        collectedAt: '2026-09-25T14:02:18.000Z',
        acquisitionMethod: 'exa_search',
      },
      founders: {
        value: ['Aravind Srinivas', 'Denis Yarats', 'Johnny Ho', 'Andy Konwinski'],
        supportState: 'supported',
        sourceUrl: 'https://blog.perplexity.ai/about',
        snippet: 'Perplexity was founded in August 2022 by Aravind Srinivas, Denis Yarats, Johnny Ho, and Andy Konwinski.',
        collectedAt: '2026-09-25T14:02:40.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      headquarters: {
        value: 'San Francisco, CA',
        supportState: 'supported',
        sourceUrl: 'https://blog.perplexity.ai/about',
        snippet: 'Headquartered in San Francisco, California.',
        collectedAt: '2026-09-25T14:02:40.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      verified_website: {
        value: 'https://perplexity.ai',
        supportState: 'supported',
        sourceUrl: 'https://perplexity.ai',
        snippet: 'Direct canonical web address.',
        collectedAt: '2026-09-25T14:02:45.000Z',
        acquisitionMethod: 'exa_search',
      },
      technical_focus: {
        value: 'Conversational Answer Engine & Live Web Grounding',
        supportState: 'inferred',
        sourceUrl: 'https://blog.perplexity.ai',
        snippet: 'Derived from platform capabilities and published index architecture.',
        collectedAt: '2026-09-25T14:02:50.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      premium_telemetry: {
        value: null,
        supportState: 'missing',
        snippet: 'Telemetry not available within allocated per-call ceiling ($0.02).',
        collectedAt: '2026-09-25T14:04:12.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
    },
    createdAt: '2026-09-25T14:06:00.000Z',
    updatedAt: '2026-09-25T14:06:30.000Z',
  },
  {
    id: 'rec-kyros-03',
    workflowId: 'wf-ai-startups',
    runId: 'run-ai-startups-1',
    data: {
      company_name: 'Baseten',
      funding_amount_usd: 40000000,
      stage: 'Series B',
      founders: ['Tuhin Srivastava', 'Amir Haghighat', 'Philip Kiely'],
      headquarters: 'San Francisco, CA',
      verified_website: 'https://baseten.co',
      technical_focus: 'High-throughput LLM Serverless Inference Infrastructure',
      premium_telemetry: 'Truss engine p99 cold start: 1.2s, L40S throughput: 110 tok/s',
    },
    evidence: {
      company_name: {
        value: 'Baseten',
        supportState: 'supported',
        sourceUrl: 'https://news.crunchbase.com/ai-robotics/baseten-series-b-inference-infrastructure/',
        snippet: 'Baseten scores $40M Series B for AI model inference platform.',
        collectedAt: '2026-09-25T14:02:22.000Z',
        acquisitionMethod: 'exa_search',
      },
      funding_amount_usd: {
        value: 40000000,
        supportState: 'supported',
        sourceUrl: 'https://news.crunchbase.com/ai-robotics/baseten-series-b-inference-infrastructure/',
        snippet: '...raised $40 million in Series B funding co-led by IVP and Spark Capital.',
        collectedAt: '2026-09-25T14:02:22.000Z',
        acquisitionMethod: 'exa_search',
      },
      stage: {
        value: 'Series B',
        supportState: 'supported',
        sourceUrl: 'https://news.crunchbase.com/ai-robotics/baseten-series-b-inference-infrastructure/',
        snippet: 'Series B announced March 2024.',
        collectedAt: '2026-09-25T14:02:22.000Z',
        acquisitionMethod: 'exa_search',
      },
      founders: {
        value: ['Tuhin Srivastava', 'Amir Haghighat', 'Philip Kiely'],
        supportState: 'partially_supported',
        sourceUrl: 'https://www.baseten.co/team',
        snippet: 'Founded by Tuhin Srivastava and Amir Haghighat; Philip Kiely joined as founding core engineer.',
        collectedAt: '2026-09-25T14:02:55.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      headquarters: {
        value: 'San Francisco, CA',
        supportState: 'supported',
        sourceUrl: 'https://www.baseten.co/team',
        snippet: 'Based in the Mission district of San Francisco.',
        collectedAt: '2026-09-25T14:02:55.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      verified_website: {
        value: 'https://baseten.co',
        supportState: 'supported',
        sourceUrl: 'https://baseten.co',
        snippet: 'Verified canonical site.',
        collectedAt: '2026-09-25T14:02:58.000Z',
        acquisitionMethod: 'exa_search',
      },
      technical_focus: {
        value: 'High-throughput LLM Serverless Inference Infrastructure',
        supportState: 'supported',
        sourceUrl: 'https://www.baseten.co/blog/announcing-series-b',
        snippet: 'Building fastest dedicated serverless infra for open source models.',
        collectedAt: '2026-09-25T14:03:02.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      premium_telemetry: {
        value: 'Truss engine p99 cold start: 1.2s, L40S throughput: 110 tok/s',
        supportState: 'supported',
        sourceUrl: 'https://basescan.org/tx/0x45a9018e698fa10b78c129486c91a029384bb290918c5e93fa12847a90b1c59e',
        sourceTitle: 'x402 Verified Benchmark Telemetry (Base Sepolia)',
        snippet: 'Audited benchmark feed settled via viem platform treasury.',
        collectedAt: '2026-09-25T14:04:30.000Z',
        acquisitionMethod: 'x402_paid',
        costUsd: 0.015,
        transactionReceipt: {
          hash: '0x45a9018e698fa10b78c129486c91a029384bb290918c5e93fa12847a90b1c59e',
          network: 'Base Sepolia (84532)',
          status: 'confirmed',
          resourceUri: 'kyros-demo://premium-eval/baseten-benchmarks',
          amountUsd: 0.015,
        },
      },
    },
    createdAt: '2026-09-25T14:06:00.000Z',
    updatedAt: '2026-09-25T14:06:30.000Z',
  },
  {
    id: 'rec-kyros-04',
    workflowId: 'wf-ai-startups',
    runId: 'run-ai-startups-1',
    data: {
      company_name: 'Poolside AI',
      funding_amount_usd: 500000000,
      stage: 'Series B',
      founders: ['Jason Warner', 'Eiso Kant'],
      headquarters: 'Paris, France',
      verified_website: 'https://poolside.ai',
      technical_focus: 'Frontier AI models for software development',
      premium_telemetry: null,
    },
    evidence: {
      company_name: {
        value: 'Poolside AI',
        supportState: 'supported',
        sourceUrl: 'https://www.reuters.com/technology/ai-startup-poolside-raises-500-million-series-b-2024-10-02/',
        snippet: 'AI startup Poolside raises $500 million Series B at $3 billion valuation.',
        collectedAt: '2026-09-25T14:02:30.000Z',
        acquisitionMethod: 'exa_search',
      },
      funding_amount_usd: {
        value: 500000000,
        supportState: 'supported',
        sourceUrl: 'https://www.reuters.com/technology/ai-startup-poolside-raises-500-million-series-b-2024-10-02/',
        snippet: '...closed $500 million in a new funding round led by Bain Capital Crypto.',
        collectedAt: '2026-09-25T14:02:30.000Z',
        acquisitionMethod: 'exa_search',
      },
      stage: {
        value: 'Series B',
        supportState: 'supported',
        sourceUrl: 'https://www.reuters.com/technology/ai-startup-poolside-raises-500-million-series-b-2024-10-02/',
        snippet: 'Series B closed October 2024.',
        collectedAt: '2026-09-25T14:02:30.000Z',
        acquisitionMethod: 'exa_search',
      },
      founders: {
        value: ['Jason Warner', 'Eiso Kant'],
        supportState: 'supported',
        sourceUrl: 'https://poolside.ai/about',
        snippet: 'Founded by former GitHub CTO Jason Warner and tech entrepreneur Eiso Kant.',
        collectedAt: '2026-09-25T14:03:05.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      headquarters: {
        value: 'Paris, France',
        supportState: 'supported',
        sourceUrl: 'https://poolside.ai/about',
        snippet: 'Operating out of Paris and San Francisco.',
        collectedAt: '2026-09-25T14:03:05.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      verified_website: {
        value: 'https://poolside.ai',
        supportState: 'supported',
        sourceUrl: 'https://poolside.ai',
        snippet: 'Canonical URL.',
        collectedAt: '2026-09-25T14:03:10.000Z',
        acquisitionMethod: 'exa_search',
      },
      technical_focus: {
        value: 'Frontier AI models for software development',
        supportState: 'supported',
        sourceUrl: 'https://poolside.ai',
        snippet: 'Building foundational models to accelerate human software creation.',
        collectedAt: '2026-09-25T14:03:15.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      premium_telemetry: {
        value: null,
        supportState: 'missing',
        snippet: 'No public or paid benchmark access available at collection time.',
        collectedAt: '2026-09-25T14:04:30.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
    },
    createdAt: '2026-09-25T14:06:00.000Z',
    updatedAt: '2026-09-25T14:06:30.000Z',
  },
  {
    id: 'rec-kyros-05',
    workflowId: 'wf-ai-startups',
    runId: 'run-ai-startups-1',
    data: {
      company_name: 'Decagon',
      funding_amount_usd: 65000000,
      stage: 'Series B',
      founders: ['Jesse Zhang', 'Ashwin Sreenivas'],
      headquarters: 'San Francisco, CA',
      verified_website: 'https://decagon.ai',
      technical_focus: 'Enterprise Generative AI Customer Support Agents',
      premium_telemetry: null,
    },
    evidence: {
      company_name: {
        value: 'Decagon',
        supportState: 'supported',
        sourceUrl: 'https://techcrunch.com/2024/10/15/decagon-raises-65m-series-b-for-ai-customer-agents/',
        snippet: 'Decagon has raised $65 million in Series B funding led by Bain Capital Ventures.',
        collectedAt: '2026-09-25T14:02:35.000Z',
        acquisitionMethod: 'exa_search',
      },
      funding_amount_usd: {
        value: 65000000,
        supportState: 'supported',
        sourceUrl: 'https://techcrunch.com/2024/10/15/decagon-raises-65m-series-b-for-ai-customer-agents/',
        snippet: 'Total Series B: $65M.',
        collectedAt: '2026-09-25T14:02:35.000Z',
        acquisitionMethod: 'exa_search',
      },
      stage: {
        value: 'Series B',
        supportState: 'supported',
        sourceUrl: 'https://techcrunch.com/2024/10/15/decagon-raises-65m-series-b-for-ai-customer-agents/',
        snippet: 'Series B round announced October 2024.',
        collectedAt: '2026-09-25T14:02:35.000Z',
        acquisitionMethod: 'exa_search',
      },
      founders: {
        value: ['Jesse Zhang', 'Ashwin Sreenivas'],
        supportState: 'supported',
        sourceUrl: 'https://decagon.ai/team',
        snippet: 'Co-founded by Jesse Zhang and Ashwin Sreenivas.',
        collectedAt: '2026-09-25T14:03:20.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      headquarters: {
        value: 'San Francisco, CA',
        supportState: 'supported',
        sourceUrl: 'https://decagon.ai/team',
        snippet: 'Offices in San Francisco.',
        collectedAt: '2026-09-25T14:03:20.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      verified_website: {
        value: 'https://decagon.ai',
        supportState: 'supported',
        sourceUrl: 'https://decagon.ai',
        snippet: 'Canonical web URL.',
        collectedAt: '2026-09-25T14:03:25.000Z',
        acquisitionMethod: 'exa_search',
      },
      technical_focus: {
        value: 'Enterprise Generative AI Customer Support Agents',
        supportState: 'supported',
        sourceUrl: 'https://decagon.ai',
        snippet: 'Automating high-volume support interactions with human-like AI agents.',
        collectedAt: '2026-09-25T14:03:30.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
      premium_telemetry: {
        value: null,
        supportState: 'missing',
        snippet: 'Not covered in x402 latency telemetry benchmark suite.',
        collectedAt: '2026-09-25T14:04:30.000Z',
        acquisitionMethod: 'gemini_extraction',
      },
    },
    createdAt: '2026-09-25T14:06:00.000Z',
    updatedAt: '2026-09-25T14:06:30.000Z',
  },
];

export const DEMO_PRESET_PROMPTS = [
  {
    title: 'AI Infrastructure Startups (2024)',
    prompt: 'Top AI infrastructure startups founded in 2024 with funding amounts, verified founders, and benchmark telemetry',
    constraints: ['funding_amount_usd', 'stage', 'founders', 'technical_focus'],
    maxSpend: 0.05,
    allowPaid: true,
  },
  {
    title: 'Enterprise Open-Source Security',
    prompt: 'Find major enterprise sponsors and maintainers of open-source software security tooling',
    constraints: ['company_name', 'sponsored_projects', 'security_domain', 'github_org'],
    maxSpend: 0.05,
    allowPaid: false,
  },
  {
    title: 'Remote ML Engineering Teams',
    prompt: 'US and EU tech companies actively hiring remote machine learning engineers with posted salary bands',
    constraints: ['company_name', 'role_title', 'salary_range_usd', 'location_policy'],
    maxSpend: 0.10,
    allowPaid: false,
  },
  {
    title: 'Sparse / Niche Market Research',
    prompt: 'Autonomous underwater robotic mapping startups with commercial contracts',
    constraints: ['company_name', 'fleet_size', 'contract_value_usd'],
    maxSpend: 0.05,
    allowPaid: true,
  },
];
